# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3bd51ea4b27f1c661b01dae6a183631b"
name = "product-tag-manager"
handle = "product-tag-manager-7"
application_url = "https://skills-assisted-concentrate-labor.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://skills-assisted-concentrate-labor.trycloudflare.com/auth/callback",
  "https://skills-assisted-concentrate-labor.trycloudflare.com/auth/shopify/callback",
  "https://skills-assisted-concentrate-labor.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
